#!/bin/bash

connect_device() {
    bluetooth_device=$(bluetoothctl devices | dmenu -l 5 -i -p "Choose device: ")
    if [ -z "$bluetooth_device" ]; then
        notify-send "MoonMoon" "No device selected."
        return
    fi
    bluetooth_device_mac=$(echo $bluetooth_device | awk '{print $2}')
    if bluetoothctl connect "$bluetooth_device_mac"; then
        notify-send "MoonMoon" "Connected to $bluetooth_device."
    else
        notify-send "MoonMoon" "Failed to connect to $bluetooth_device."
    fi
}

disconnect_device() {
	bluetoothctl disconnect
}

choice=$(echo -e "Connect device\\nDisconnect device" | dmenu -l 4 -i -p "Choose command: ")
case "$choice" in
    "Connect device") connect_device ;;
    "Disconnect device") disconnect_device ;;
    *) notify-send "MoonMoon" "Invalid choice." ;;
esac
